import { StyleSheet } from "react-native";
import { wp, hp } from "../dimensions.js";
import { C1, C2, C3, C4, C5, C6, C7 } from "../colors.js";

const styles = StyleSheet.create({
  backButtonContainer: {
    top: 25,
    right: 100,
  },
  backgroundContainer: {
    flex: 1,
    position: "absolute",
    top: 0,
    bottom: 0,
    left: 0,
    right: 0,
    zIndex: -1,
  },
  backgroundImage: {
    flex: 1,
    resizeMode: "cover",
    marginBottom: 205,
  },
  button: {
    alignSelf: "stretch",
    marginHorizontal: hp(12.5),
    marginVertical: wp(5),
    backgroundColor: "white",
    padding: 10,
    borderRadius: 10,
    alignItems: "center",
    borderColor : C5,
    borderWidth : 2,
  },
  buttonText: {
    color: C3,
    fontWeight: "bold",
    textShadowColor: C2,
    textShadowOffset: { width: -1, height: 1 },
    textShadowRadius: 3,
  },
  container: {
    flex: 1,
    backgroundColor: C6,
  },
  containerPartenaires: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-evenly",
    alignItems: "center",
    padding: hp(2),
  },
  content: {
    flex: 1,
    padding: hp(1.2),
    marginHorizontal: hp(1),
  },
  contentContact: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "white",
    borderRadius: 20,
    marginHorizontal: wp(10),
    marginVertical: hp(15),
    padding: hp(3),
    borderColor : C5,
    borderWidth : 2,
  },
  contentPlus: {
    flex: 1,
    alignItems: "center",
    justifyContent: "flex-start",
    backgroundColor: C7,
    padding: hp(1.5),
    marginHorizontal: wp(2),
    borderRadius: 10,
    marginVertical: hp(2),
    borderColor : C2,
    borderWidth : 2,
  },
  contentText: {
    backgroundColor: "white",
    borderRadius: 10,
    borderColor: C5,
    borderWidth: 2,
    alignItems: "flex-start",
  },
  email: {
    color: "blue",
    textDecorationLine: "underline",
    marginTop: 25,
    fontSize: 18,
  },
  header: {
    alignItems: "center",
    marginTop: hp(2.5),
  },
  icon: {
    marginRight: hp(1.5),
    color: C3,
  },
  iconPlus: {
    width: 30,
  },
  image: {
    width: wp(20),
    height: hp(10),
    resizeMode: "contain",
  },
  imageObjetsInt: {
    width: wp(90),
    height: hp(28),
    resizeMode: "contain",
  },
  imgContainer: {
    alignItems: "center",
    justifyContent: "center",
    width: "40%",
    padding: hp(2),
    margin: hp(1),
    backgroundColor: "rgba(255, 255, 255, 0.7)",
  },
  infosContainer: {
    padding: hp(1.5),
    backgroundColor: "white",
    borderRadius: 10,
    borderColor: C5,
    borderWidth: 2,
    marginVertical: hp(1.5),
  },
  plusButton: {
    alignSelf: "stretch",
    marginHorizontal: hp(12.5),
    marginVertical: wp(5),
    backgroundColor: "white",
    padding: 10,
    borderRadius: 10,
    alignItems: "center",
    borderColor : C5,
    borderWidth : 2,
  },
  plusButtonText: {
    color: C3,
    fontWeight: "bold",
    textShadowColor: C2,
    textShadowOffset: { width: -1, height: 1 },
    textShadowRadius: 3,
  },
  plusTitle: {
    fontSize: 30,
    fontWeight: "bold",
    marginBottom: wp(3),
    textShadowColor: C3,
    textShadowOffset: { width: -1, height: 1 },
    textShadowRadius: 3,
  },
  section: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: hp(1.5),
    marginTop: hp(3.8),
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: "bold",
    color: C3,
    textShadowColor: C2,
    textShadowOffset: { width: -1, height: 1 },
    textShadowRadius: 3,
  },
  separator: {
    borderBottomColor: C7,
    borderBottomWidth: 1,
    marginBottom: wp(3),
  },
  sousText: {
    flexDirection: "row",
  },
  sousTextIcon: {
    marginRight: 12,
    marginBottom: 12,
  },
  sousTextTitle: {
    fontSize: 16,
    paddingBottom: 10,
    height: 30,
    color: C3,
    textShadowColor: C2,
    textShadowOffset: { width: -1, height: 1 },
    textShadowRadius: 3,
  },
  textInfos: {
    fontSize: 20,
    fontWeight: "bold",
    marginBottom: wp(8),
    textAlign: "center",
    color: C3,
    textShadowColor: C2,
    textShadowOffset: { width: -1, height: 1 },
    textShadowRadius: 3,
  },
  textSousTitre: {
    fontWeight: "bold",
    textShadowColor: C3,
    textShadowOffset: { width: -1, height: 1 },
    textShadowRadius: 3,
  },
  textContact: {
    fontSize: 15,
  },
  title: {
    fontSize: 24,
    fontWeight: "bold",
    textShadowColor: C3,
    textShadowOffset: { width: -1, height: 1 },
    textShadowRadius: 3,
  },
  titleContact: {
    fontSize: 22,
    fontWeight: "bold",
    marginBottom: 28,
    paddingBottom: 10,
    color: C3,
    textShadowColor: C2,
    textShadowOffset: { width: -1, height: 1 },
    textShadowRadius: 3,

  },
  voirPlus: {
    color: C3,
    marginTop: hp(1.5),
    alignSelf: "center",
    fontWeight: "bold",
  },
});

export default styles;
