-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;

CREATE TABLE IF NOT EXISTS artistes.styles_musicaux
(
    style_musicalid serial NOT NULL,
    style_musical character varying(50) NOT NULL,
    PRIMARY KEY (style_musicalid)
);

CREATE TABLE IF NOT EXISTS artistes.origines
(
    origineid serial NOT NULL,
    origine character varying(50) NOT NULL,
    PRIMARY KEY (origineid)
);

CREATE TABLE IF NOT EXISTS artistes.scenes
(
    sceneid serial NOT NULL,
    scene character varying(50) NOT NULL,
    PRIMARY KEY (sceneid)
);

CREATE TABLE IF NOT EXISTS artistes.artistes
(
    artisteid serial NOT NULL,
    artiste character varying(100) NOT NULL,
    datehdebut timestamp without time zone NOT NULL,
    duree time without time zone NOT NULL,
    description text NOT NULL,
    imageurl text NOT NULL,
	sceneid integer REFERENCES artistes.scenes,
    style_musicalid integer REFERENCES artistes.styles_musicaux,
    origineid integer REFERENCES artistes.origines,
    CONSTRAINT artiste_pkey PRIMARY KEY (artisteid)
);

END;

-- suppression de toutes les tables
DROP TABLE IF EXISTS artistes.styles_musicaux_artistes;
DROP TABLE IF EXISTS artistes.origines_artistes;
DROP TABLE IF EXISTS artistes.artistes;
DROP TABLE IF EXISTS artistes.scenes;
DROP TABLE IF EXISTS artistes.styles_musicaux;
DROP TABLE IF EXISTS artistes.origines;

SELECT *
FROM artistes.artistes

SELECT *
FROM artistes.styles_musicaux

SELECT *
FROM artistes.origines

SELECT *
FROM artistes.scenes

DELETE FROM artistes.artistes
WHERE artisteid > 0;

DELETE FROM artistes.styles_musicaux
WHERE style_musicalid > 0;

DELETE FROM artistes.origines
WHERE origineid > 0;

DELETE FROM artistes.scenes
WHERE sceneid > 0;

INSERT INTO artistes.styles_musicaux (style_musical)
VALUES ('RAP');

INSERT INTO artistes.origines (origine)
VALUES ('FRANCE');

INSERT INTO artistes.scenes (scene)
VALUES ('TEST');

INSERT INTO artistes.artistes (artiste, datehdebut, duree, description, imageurl, sceneid, style_musicalid, origineid)
VALUES
    ('Artiste 1', '2023-08-08 15:00:00', '02:00:00', 'Description de l''artiste 1', 'url_image_1', 1, 1, 1),
    ('Artiste 2', '2023-08-09 18:30:00', '01:30:00', 'Description de l''artiste 2', 'url_image_2', 1, 1, 1),
    ('Artiste 3', '2023-08-10 14:00:00', '02:30:00', 'Description de l''artiste 3', 'url_image_3', 1, 1, 1);

SELECT
    a.artisteid,
    a.artiste,
    a.datehdebut,
    a.duree,
    a.description,
    a.imageurl,
    s.sceneid,
    s.scene,
    sm.style_musicalid,
    sm.style_musical,
    o.origineid,
    o.origine
FROM
    artistes.artistes a
    LEFT JOIN artistes.scenes s ON a.sceneid = s.sceneid
    LEFT JOIN artistes.styles_musicaux sm ON a.style_musicalid = sm.style_musicalid
    LEFT JOIN artistes.origines o ON a.origineid = o.origineid;
