-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS clients.clients
(
    id serial NOT NULL,
    prenom character varying(50) NOT NULL,
    nom character varying(100) NOT NULL,
    adresse text NOT NULL,
    pays character varying(50) NOT NULL,
    ville character varying(50) NOT NULL,
    codepostal character varying(5) NOT NULL,
    departement character varying(50) NOT NULL,
    email character varying(100) NOT NULL,
    telephone character varying(10) NOT NULL,
    motdepasse character varying(100) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS clients.commandes
(
    id integer NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS clients.commandes_clients
(
    commandes_id integer NOT NULL,
    clients_id serial NOT NULL
);

ALTER TABLE IF EXISTS clients.commandes_clients
    ADD FOREIGN KEY (commandes_id)
    REFERENCES clients.commandes (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS clients.commandes_clients
    ADD FOREIGN KEY (clients_id)
    REFERENCES clients.clients (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;


DROP TABLE IF EXISTS clients.commandes_clients;
DROP TABLE IF EXISTS clients.clients;
DROP TABLE IF EXISTS clients.commandes;


BEGIN;

INSERT INTO clients.clients (id, prenom, nom, adresse, pays, ville, codepostal, departement, email, telephone, motdepasse)
	VALUES 
	(1, 'John', 'Doe', '123 Main Street', 'France', 'Paris', '75001', 'Paris', 'john.doe@example.com', '0612345678', 'password'),
	(2, 'Jane', 'Doe', '456 Elm Street', 'United States', 'New York', '10001', 'New York', 'jane.doe@example.com', '0123456789', 'password'),
	(3, 'Pierre', 'Dupont', '789 Oak Street', 'Canada', 'Montreal', '65894', 'Quebec', 'pierre.dupont@example.com', '5141234567', 'password');
	
INSERT INTO clients.commandes (id)
	VALUES (1), (2), (3), (4);
	
INSERT INTO clients.commandes_clients (commandes_id, clients_id)
	VALUES (1, 1), (2,2), (3,2), (4,3);
	
END;

select * 
from clients.clients

SELECT
    c.prenom,
    cs.id
FROM
    clients.clients AS c
JOIN
    clients.commandes_clients AS cc ON c.id = cc.clients_id
JOIN
    clients.commandes AS cs ON cc.clients_id = cs.id

DELETE FROM clients.commandes_clients;
DELETE FROM clients.commandes;
DELETE FROM clients.clients;