-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS partenaires.partenaires
(
    id serial NOT NULL,
    partenaire character varying(50) NOT NULL,
    imageurl text NOT NULL,
    sitepartenaire text NOT NULL,
    PRIMARY KEY (id)
);

INSERT INTO partenaires.partenaires (partenaire, imageurl, sitepartenaire) VALUES
('Partenaire 1', 'http://exemple.com/image1.jpg', 'http://www.sitepartenaire1.com'),
('Partenaire 2', 'http://exemple.com/image2.jpg', 'http://www.sitepartenaire2.com'),
('Partenaire 3', 'http://exemple.com/image3.jpg', 'http://www.sitepartenaire3.com'),
('Partenaire 4', 'http://exemple.com/image4.jpg', 'http://www.sitepartenaire4.com');

END;

select * from partenaires.partenaires