-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS localisations.localisations
(
    id serial,
    localisation character varying(50) NOT NULL,
    lattitude numeric(9, 6) NOT NULL,
    longitude numeric(9, 6) NOT NULL,
    description text NOT NULL,
    PRIMARY KEY (id)
);
END;

-- Insertion de données dans la table localisations.localisations
INSERT INTO localisations.localisations (localisation, lattitude, longitude, description)
VALUES
    ('Paris', 48.8566, 2.3522, 'La capitale de la France'),
    ('New York', 40.7128, -74.0060, 'La ville qui ne dort jamais'),
    ('Tokyo', 35.682839, 139.759455, 'La métropole japonaise');

-- DROP TABLE localisations.localisations